name: Update
on:
  workflow_dispatch:
  schedule:		
    - cron:  '0 12 * * *'	
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Update Readme
        run: curl -s -o README.md $REFLECTORS_HOST/api/generateReport
        env:
          REFLECTORS_HOST: ${{ secrets.REFLECTORS_HOST }}
          
      - name: Update UR
        run: |
          curl -s -o UR_CALLS/Global.csv $REFLECTORS_HOST/api/ur
          curl -s $REFLECTORS_HOST/api/reflectorCountries | jq '.[].code' | while read -r code; do curl -s -o UR_CALLS/$code.csv $REFLECTORS_HOST/api/ur/$code; done
          
        env:
          REFLECTORS_HOST: ${{ secrets.REFLECTORS_HOST }}
          
      - name: Commit
        run: |
          git config --global user.email "github_actions@gmail.com"
          git config --global user.name "Github Actions"
          git add -A
          git commit -m "Update"
          git push
